### ISSUE TITLE
Actions CI Script fails.

### ISSUE THREAD

**Issue by ferry-clareai** [kenszeapp/CovidDemo#5]
It seems like trying to run integration tests in CI script, and eventually the MongoDb is not available.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/101232802/175256331-f7a0b9b3-1bc6-4b0b-96a5-d8ee8396fb26.png">

**Comment by genewu2022** [comment]
@kenszeapp can you reply?

**Comment by kenszeapp** [comment]
Sorry, did't aware question on here. 

The build action has been modified.  Now the action should work properly.  

I try to run DB-App Integration test, so added run mongo db docker with Github actoin.  Not sure isn't a properly way but work. 

![image](https://user-images.githubusercontent.com/25942774/175865918-928d162e-a0e5-4904-85d1-cb81395a4ec5.png)

**Comment by ferry-clareai** [comment]
I can see the CI scripts resume to normal 2 days ago. Thanks.
